name: Hotfix Release

on:
  workflow_dispatch:

jobs:
  manual-release:
    # lack of better ways to access control a manual workflow dispatch
    if: github.actor == 'deepankarm' || github.actor == 'nan-wang'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.JINA_DEV_BOT }}
          fetch-depth: 100
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: |
          git fetch --depth=1 origin +ref/tags/*:refs/tags/*
          npm install git-release-notes
          pip install twine wheel
      - run: ./scripts/release.sh
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      - if: failure()
        run: echo "nothing to release"
      - name: bumping master version
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.JINA_DEV_BOT }}
          tags: true
